[window]
padding = {x = 32, y = 32}
decorations = "None"
opacity = 0.6
blur = true
startup_mode = "Maximized"

[cursor]
style = "Beam"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }

size = 12.0
